/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dormitory_management_system;
import java.awt.Color;

/**
 *
 * @author VENUS ANGEL
 */
public class dashbord_admin extends javax.swing.JFrame {
    
    Color DefaultColor, ClickedColor;
   

    /**
     * Creates new form dashbord_admin
     */
    public dashbord_admin() {
           initComponents();    
    DefaultColor = new Color(246,245,242);
    ClickedColor=new Color(51,51,51);
 
information_click.setBackground(DefaultColor);
Request_click.setBackground(DefaultColor);
Notification_click.setBackground(DefaultColor);
PayHist_click.setBackground(DefaultColor);
Month_Earn_click.setBackground(DefaultColor);
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        information_click = new javax.swing.JLabel();
        Request_click = new javax.swing.JLabel();
        Notification_click = new javax.swing.JLabel();
        PayHist_click = new javax.swing.JLabel();
        Month_Earn_click = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(246, 245, 242));
        jPanel7.setToolTipText("");

        information_click.setBackground(new java.awt.Color(153, 153, 153));
        information_click.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        information_click.setForeground(new java.awt.Color(0, 0, 0));
        information_click.setText("            Information");
        information_click.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        information_click.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                information_clickMouseClicked(evt);
            }
        });

        Request_click.setBackground(new java.awt.Color(153, 153, 153));
        Request_click.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Request_click.setForeground(new java.awt.Color(0, 0, 0));
        Request_click.setText("               Request");
        Request_click.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        Notification_click.setBackground(new java.awt.Color(21, 52, 72));
        Notification_click.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Notification_click.setForeground(new java.awt.Color(0, 0, 0));
        Notification_click.setText("            Notification");
        Notification_click.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        PayHist_click.setBackground(new java.awt.Color(21, 52, 72));
        PayHist_click.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        PayHist_click.setForeground(new java.awt.Color(0, 0, 0));
        PayHist_click.setText("        Payment History");
        PayHist_click.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        Month_Earn_click.setBackground(new java.awt.Color(21, 52, 72));
        Month_Earn_click.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        Month_Earn_click.setForeground(new java.awt.Color(0, 0, 0));
        Month_Earn_click.setText("        Monthly Earnings");
        Month_Earn_click.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(information_click, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Request_click, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(Notification_click, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(PayHist_click, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(Month_Earn_click, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(information_click, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Request_click, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Notification_click, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PayHist_click, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Month_Earn_click, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 480));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 800, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void information_clickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_information_clickMouseClicked
        // TODO add your handling code here:
        //information_click info = new information_click ();
    //    InformationFrame.removeAll();
       // InformationFrame.add(information_click).setVisible(true);

      
    }//GEN-LAST:event_information_clickMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashbord_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashbord_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashbord_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashbord_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dashbord_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Month_Earn_click;
    private javax.swing.JLabel Notification_click;
    private javax.swing.JLabel PayHist_click;
    private javax.swing.JLabel Request_click;
    private javax.swing.JLabel information_click;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables

    private static class information_click {

        public information_click() {
        }
    }
}
